// SPDX-License-Identifier: GPL-3.0-or-later
/**
 * @file isotp.h
 * @brief MBLINK compatibility facade for LINK-owned ISO-TP.
 */
#ifndef MBLINK_ISOTP_H
#define MBLINK_ISOTP_H

#include "link/isotp.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef LinkIsoTpAddressingMode MblinkIsoTpAddressingMode;
typedef LinkIsoTpTargetType MblinkIsoTpTargetType;
typedef LinkIsoTpFlowStatus MblinkIsoTpFlowStatus;
typedef LinkIsoTpResult MblinkIsoTpResult;
typedef LinkIsoTpRxState MblinkIsoTpRxState;
typedef LinkIsoTpTxState MblinkIsoTpTxState;
typedef LinkIsoTpAddress MblinkIsoTpAddress;
typedef LinkIsoTpCanFrame MblinkIsoTpCanFrame;
typedef LinkIsoTpRxConfig MblinkIsoTpRxConfig;
typedef LinkIsoTpRx MblinkIsoTpRx;
typedef LinkIsoTpTxConfig MblinkIsoTpTxConfig;
typedef LinkIsoTpTx MblinkIsoTpTx;

#define MBLINK_ISOTP_CLASSIC_CAN_DATA_LENGTH LINK_ISOTP_CLASSIC_CAN_DATA_LENGTH
#define MBLINK_ISOTP_MAX_PDU_LENGTH LINK_ISOTP_MAX_PDU_LENGTH

#define MBLINK_ISOTP_ADDRESSING_NORMAL LINK_ISOTP_ADDRESSING_NORMAL
#define MBLINK_ISOTP_ADDRESSING_EXTENDED LINK_ISOTP_ADDRESSING_EXTENDED
#define MBLINK_ISOTP_ADDRESSING_MIXED LINK_ISOTP_ADDRESSING_MIXED

#define MBLINK_ISOTP_TARGET_PHYSICAL LINK_ISOTP_TARGET_PHYSICAL
#define MBLINK_ISOTP_TARGET_FUNCTIONAL LINK_ISOTP_TARGET_FUNCTIONAL

#define MBLINK_ISOTP_FLOW_CONTINUE_TO_SEND LINK_ISOTP_FLOW_CONTINUE_TO_SEND
#define MBLINK_ISOTP_FLOW_WAIT LINK_ISOTP_FLOW_WAIT
#define MBLINK_ISOTP_FLOW_OVERFLOW LINK_ISOTP_FLOW_OVERFLOW

#define MBLINK_ISOTP_RESULT_OK LINK_ISOTP_RESULT_OK
#define MBLINK_ISOTP_RESULT_COMPLETE LINK_ISOTP_RESULT_COMPLETE
#define MBLINK_ISOTP_RESULT_WAIT_FLOW_CONTROL LINK_ISOTP_RESULT_WAIT_FLOW_CONTROL
#define MBLINK_ISOTP_RESULT_WAIT_SEPARATION LINK_ISOTP_RESULT_WAIT_SEPARATION
#define MBLINK_ISOTP_RESULT_FLOW_CONTROL_WAIT LINK_ISOTP_RESULT_FLOW_CONTROL_WAIT
#define MBLINK_ISOTP_RESULT_INVALID_ARGUMENT LINK_ISOTP_RESULT_INVALID_ARGUMENT
#define MBLINK_ISOTP_RESULT_INVALID_FRAME LINK_ISOTP_RESULT_INVALID_FRAME
#define MBLINK_ISOTP_RESULT_UNEXPECTED_FRAME LINK_ISOTP_RESULT_UNEXPECTED_FRAME
#define MBLINK_ISOTP_RESULT_WRONG_SEQUENCE LINK_ISOTP_RESULT_WRONG_SEQUENCE
#define MBLINK_ISOTP_RESULT_BUFFER_TOO_SMALL LINK_ISOTP_RESULT_BUFFER_TOO_SMALL
#define MBLINK_ISOTP_RESULT_PAYLOAD_TOO_LARGE LINK_ISOTP_RESULT_PAYLOAD_TOO_LARGE
#define MBLINK_ISOTP_RESULT_TIMEOUT LINK_ISOTP_RESULT_TIMEOUT
#define MBLINK_ISOTP_RESULT_FLOW_CONTROL_OVERFLOW LINK_ISOTP_RESULT_FLOW_CONTROL_OVERFLOW
#define MBLINK_ISOTP_RESULT_WAIT_FRAME_LIMIT LINK_ISOTP_RESULT_WAIT_FRAME_LIMIT
#define MBLINK_ISOTP_RESULT_UNSUPPORTED LINK_ISOTP_RESULT_UNSUPPORTED

#define MBLINK_ISOTP_RX_IDLE LINK_ISOTP_RX_IDLE
#define MBLINK_ISOTP_RX_RECEIVING LINK_ISOTP_RX_RECEIVING
#define MBLINK_ISOTP_RX_COMPLETE LINK_ISOTP_RX_COMPLETE
#define MBLINK_ISOTP_RX_FAILED LINK_ISOTP_RX_FAILED

#define MBLINK_ISOTP_TX_IDLE LINK_ISOTP_TX_IDLE
#define MBLINK_ISOTP_TX_WAIT_FLOW_CONTROL LINK_ISOTP_TX_WAIT_FLOW_CONTROL
#define MBLINK_ISOTP_TX_SENDING LINK_ISOTP_TX_SENDING
#define MBLINK_ISOTP_TX_COMPLETE LINK_ISOTP_TX_COMPLETE
#define MBLINK_ISOTP_TX_FAILED LINK_ISOTP_TX_FAILED

#define mblink_isotp_result_name link_isotp_result_name
#define mblink_isotp_rx_state_name link_isotp_rx_state_name
#define mblink_isotp_tx_state_name link_isotp_tx_state_name
#define mblink_isotp_address_is_valid link_isotp_address_is_valid
#define mblink_isotp_stmin_to_us link_isotp_stmin_to_us
#define mblink_isotp_rx_init link_isotp_rx_init
#define mblink_isotp_rx_reset link_isotp_rx_reset
#define mblink_isotp_rx_feed link_isotp_rx_feed
#define mblink_isotp_rx_tick link_isotp_rx_tick
#define mblink_isotp_rx_payload link_isotp_rx_payload
#define mblink_isotp_tx_init link_isotp_tx_init
#define mblink_isotp_tx_reset link_isotp_tx_reset
#define mblink_isotp_tx_start link_isotp_tx_start
#define mblink_isotp_tx_accept_flow_control link_isotp_tx_accept_flow_control
#define mblink_isotp_tx_next link_isotp_tx_next
#define mblink_isotp_tx_tick link_isotp_tx_tick

#ifdef __cplusplus
}
#endif

#endif
