// SPDX-License-Identifier: GPL-3.0-or-later
/**
 * @file kwp2000.h
 * @brief MBLINK compatibility aliases for LINK's shared ISO 14230-3 engine.
 */
#ifndef MBLINK_KWP2000_H
#define MBLINK_KWP2000_H

#include "link/kwp2000.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef LinkKwp2000Result MblinkKwp2000Result;
typedef LinkKwp2000ResponseKind MblinkKwp2000ResponseKind;
typedef LinkKwp2000Response MblinkKwp2000Response;
typedef LinkKwp2000CommonIdentifierRecord MblinkKwp2000CommonIdentifierRecord;
typedef LinkKwp2000EcuIdentificationRecord MblinkKwp2000EcuIdentificationRecord;
typedef LinkKwp2000Dtc MblinkKwp2000Dtc;
typedef LinkKwp2000DtcList MblinkKwp2000DtcList;

#define MBLINK_KWP2000_SERVICE_READ_DTC_BY_STATUS LINK_KWP2000_SERVICE_READ_DTC_BY_STATUS
#define MBLINK_KWP2000_SERVICE_READ_ECU_IDENTIFICATION LINK_KWP2000_SERVICE_READ_ECU_IDENTIFICATION
#define MBLINK_KWP2000_SERVICE_READ_DATA_BY_COMMON_IDENTIFIER LINK_KWP2000_SERVICE_READ_DATA_BY_COMMON_IDENTIFIER
#define MBLINK_KWP2000_SERVICE_TESTER_PRESENT LINK_KWP2000_SERVICE_TESTER_PRESENT
#define MBLINK_KWP2000_SERVICE_NEGATIVE_RESPONSE LINK_KWP2000_SERVICE_NEGATIVE_RESPONSE
#define MBLINK_KWP2000_DTC_REQUEST_STORED_AND_STATUS LINK_KWP2000_DTC_REQUEST_STORED_AND_STATUS
#define MBLINK_KWP2000_DTC_GROUP_ALL LINK_KWP2000_DTC_GROUP_ALL
#define MBLINK_KWP2000_RESULT_OK LINK_KWP2000_RESULT_OK
#define MBLINK_KWP2000_RESULT_NEGATIVE_RESPONSE LINK_KWP2000_RESULT_NEGATIVE_RESPONSE
#define MBLINK_KWP2000_RESULT_MALFORMED_PDU LINK_KWP2000_RESULT_MALFORMED_PDU
#define MBLINK_KWP2000_RESULT_UNEXPECTED_RESPONSE LINK_KWP2000_RESULT_UNEXPECTED_RESPONSE

#define mblink_kwp2000_result_name link_kwp2000_result_name
#define mblink_kwp2000_decode_response link_kwp2000_decode_response
#define mblink_kwp2000_build_tester_present_request link_kwp2000_build_tester_present_request
#define mblink_kwp2000_decode_tester_present_response link_kwp2000_decode_tester_present_response
#define mblink_kwp2000_build_read_common_identifier_request link_kwp2000_build_read_common_identifier_request
#define mblink_kwp2000_decode_read_common_identifier_response link_kwp2000_decode_read_common_identifier_response
#define mblink_kwp2000_build_read_ecu_identification_request link_kwp2000_build_read_ecu_identification_request
#define mblink_kwp2000_decode_read_ecu_identification_response link_kwp2000_decode_read_ecu_identification_response
#define mblink_kwp2000_build_read_dtc_by_status_request link_kwp2000_build_read_dtc_by_status_request
#define mblink_kwp2000_decode_read_dtc_by_status_response link_kwp2000_decode_read_dtc_by_status_response

#ifdef __cplusplus
}
#endif

#endif
