// SPDX-License-Identifier: GPL-3.0-or-later
#ifndef MBLINK_PARAMETER_STORE_H
#define MBLINK_PARAMETER_STORE_H

#include "mblink/parameter.h"
#include "link/parameter_store.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef LinkParameterStoreResult MblinkParameterStoreResult;
typedef LinkParameterStoreSlot MblinkParameterStoreSlot;
typedef LinkParameterStore MblinkParameterStore;

#define MBLINK_PARAMETER_STORE_DEFINITION_CAPACITY LINK_PARAMETER_STORE_DEFINITION_CAPACITY
#define MBLINK_PARAMETER_STORE_HISTORY_CAPACITY LINK_PARAMETER_STORE_HISTORY_CAPACITY
#define MBLINK_PARAMETER_STORE_OK LINK_PARAMETER_STORE_OK
#define MBLINK_PARAMETER_STORE_INVALID_ARGUMENT LINK_PARAMETER_STORE_INVALID_ARGUMENT
#define MBLINK_PARAMETER_STORE_FULL LINK_PARAMETER_STORE_FULL
#define MBLINK_PARAMETER_STORE_DUPLICATE_KEY LINK_PARAMETER_STORE_DUPLICATE_KEY
#define MBLINK_PARAMETER_STORE_DUPLICATE_STABLE_KEY LINK_PARAMETER_STORE_DUPLICATE_STABLE_KEY
#define MBLINK_PARAMETER_STORE_NOT_FOUND LINK_PARAMETER_STORE_NOT_FOUND
#define MBLINK_PARAMETER_STORE_DEFINITION_MISMATCH LINK_PARAMETER_STORE_DEFINITION_MISMATCH

#define mblink_parameter_store_result_name link_parameter_store_result_name
#define mblink_parameter_store_init link_parameter_store_init
#define mblink_parameter_store_clear_samples link_parameter_store_clear_samples
#define mblink_parameter_store_register link_parameter_store_register
#define mblink_parameter_store_definition_count link_parameter_store_definition_count
#define mblink_parameter_store_definition_at link_parameter_store_definition_at
#define mblink_parameter_store_definition link_parameter_store_definition
#define mblink_parameter_store_definition_for_stable_key link_parameter_store_definition_for_stable_key
#define mblink_parameter_store_set_favourite link_parameter_store_set_favourite
#define mblink_parameter_store_is_favourite link_parameter_store_is_favourite
#define mblink_parameter_store_record link_parameter_store_record
#define mblink_parameter_store_latest link_parameter_store_latest
#define mblink_parameter_store_history_count link_parameter_store_history_count
#define mblink_parameter_store_total_sample_count link_parameter_store_total_sample_count
#define mblink_parameter_store_history_at link_parameter_store_history_at

#ifdef __cplusplus
}
#endif
#endif
