// SPDX-License-Identifier: GPL-3.0-or-later
#ifndef MBLINK_SCHEDULER_H
#define MBLINK_SCHEDULER_H

#include "mblink/obd2.h"
#include "mblink/parameter.h"
#include "link/scheduler.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef LinkSchedulerPriority MblinkSchedulerPriority;
typedef LinkSchedulerResult MblinkSchedulerResult;
typedef LinkSchedulerNextResult MblinkSchedulerNextResult;
typedef LinkSchedulerItem MblinkSchedulerItem;
typedef LinkScheduler MblinkScheduler;
typedef LinkSchedulerDispatch MblinkSchedulerDispatch;

#define MBLINK_SCHEDULER_MAX_ITEMS LINK_SCHEDULER_MAX_ITEMS
#define MBLINK_SCHEDULER_PRIORITY_LOW LINK_SCHEDULER_PRIORITY_LOW
#define MBLINK_SCHEDULER_PRIORITY_NORMAL LINK_SCHEDULER_PRIORITY_NORMAL
#define MBLINK_SCHEDULER_PRIORITY_HIGH LINK_SCHEDULER_PRIORITY_HIGH
#define MBLINK_SCHEDULER_PRIORITY_CRITICAL LINK_SCHEDULER_PRIORITY_CRITICAL
#define MBLINK_SCHEDULER_RESULT_OK LINK_SCHEDULER_RESULT_OK
#define MBLINK_SCHEDULER_RESULT_INVALID_ARGUMENT LINK_SCHEDULER_RESULT_INVALID_ARGUMENT
#define MBLINK_SCHEDULER_RESULT_FULL LINK_SCHEDULER_RESULT_FULL
#define MBLINK_SCHEDULER_RESULT_DUPLICATE LINK_SCHEDULER_RESULT_DUPLICATE
#define MBLINK_SCHEDULER_RESULT_NOT_FOUND LINK_SCHEDULER_RESULT_NOT_FOUND
#define MBLINK_SCHEDULER_NEXT_READY LINK_SCHEDULER_NEXT_READY
#define MBLINK_SCHEDULER_NEXT_WAITING LINK_SCHEDULER_NEXT_WAITING
#define MBLINK_SCHEDULER_NEXT_PAUSED LINK_SCHEDULER_NEXT_PAUSED
#define MBLINK_SCHEDULER_NEXT_EMPTY LINK_SCHEDULER_NEXT_EMPTY
#define MBLINK_SCHEDULER_NEXT_INVALID_ARGUMENT LINK_SCHEDULER_NEXT_INVALID_ARGUMENT

#define mblink_scheduler_result_name link_scheduler_result_name
#define mblink_scheduler_next_result_name link_scheduler_next_result_name
#define mblink_scheduler_init link_scheduler_init
#define mblink_scheduler_add_parameter link_scheduler_add_parameter
#define mblink_scheduler_set_parameter_enabled link_scheduler_set_parameter_enabled
#define mblink_scheduler_add link_scheduler_add
#define mblink_scheduler_set_enabled link_scheduler_set_enabled
#define mblink_scheduler_set_paused link_scheduler_set_paused
#define mblink_scheduler_next link_scheduler_next
#define mblink_scheduler_mark_dispatched link_scheduler_mark_dispatched

MblinkSchedulerResult mblink_scheduler_configure_standard_obd2(
    MblinkScheduler *scheduler,
    const MblinkObd2PidSet *supported,
    uint64_t first_due_ms);

#ifdef __cplusplus
}
#endif
#endif
