// SPDX-License-Identifier: GPL-3.0-or-later
#ifndef MBLINK_TELEMETRY_H
#define MBLINK_TELEMETRY_H

#include "mblink/elm327.h"
#include "mblink/obd2.h"
#include "link/telemetry.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef LinkTelemetrySample MblinkTelemetrySample;
typedef LinkTelemetryTranscriptEntry MblinkTelemetryTranscriptEntry;
typedef LinkTelemetryStore MblinkTelemetryStore;
typedef LinkTelemetrySessionMetadata MblinkTelemetrySessionMetadata;
typedef LinkTelemetryTextSink MblinkTelemetryTextSink;
typedef LinkTelemetryRecorder MblinkTelemetryRecorder;

#define MBLINK_TELEMETRY_HISTORY_CAPACITY LINK_TELEMETRY_HISTORY_CAPACITY
#define MBLINK_TELEMETRY_ADAPTER_TEXT_LENGTH LINK_TELEMETRY_ADAPTER_TEXT_LENGTH
#define MBLINK_TELEMETRY_VEHICLE_TEXT_LENGTH LINK_TELEMETRY_VEHICLE_TEXT_LENGTH
#define MBLINK_TELEMETRY_TRANSCRIPT_CAPACITY LINK_TELEMETRY_TRANSCRIPT_CAPACITY
#define MBLINK_TELEMETRY_TRANSCRIPT_COMMAND_LENGTH LINK_TELEMETRY_TRANSCRIPT_COMMAND_LENGTH
#define MBLINK_TELEMETRY_TRANSCRIPT_RESPONSE_LENGTH LINK_TELEMETRY_TRANSCRIPT_RESPONSE_LENGTH

#define mblink_telemetry_store_init link_telemetry_store_init
#define mblink_telemetry_store_clear_samples link_telemetry_store_clear_samples
#define mblink_telemetry_store_latest link_telemetry_store_latest
#define mblink_telemetry_store_history_count link_telemetry_store_history_count
#define mblink_telemetry_store_total_sample_count link_telemetry_store_total_sample_count
#define mblink_telemetry_store_history_at link_telemetry_store_history_at
#define mblink_telemetry_store_set_favourite link_telemetry_store_set_favourite
#define mblink_telemetry_store_is_favourite link_telemetry_store_is_favourite
#define mblink_telemetry_store_transcript_count link_telemetry_store_transcript_count
#define mblink_telemetry_store_transcript_at link_telemetry_store_transcript_at
#define mblink_telemetry_session_metadata_init link_telemetry_session_metadata_init
#define mblink_telemetry_session_metadata_set_adapter link_telemetry_session_metadata_set_adapter
#define mblink_telemetry_session_metadata_set_vehicle link_telemetry_session_metadata_set_vehicle
#define mblink_telemetry_session_metadata_finish link_telemetry_session_metadata_finish
#define mblink_telemetry_recorder_init link_telemetry_recorder_init
#define mblink_telemetry_recorder_finish link_telemetry_recorder_finish

bool mblink_telemetry_store_record(MblinkTelemetryStore *store, uint64_t timestamp_ms, const MblinkObd2Sample *measurement);
bool mblink_telemetry_store_record_transcript(MblinkTelemetryStore *store, uint64_t timestamp_ms, const char *command, const MblinkElm327Response *response);
bool mblink_telemetry_recorder_begin(MblinkTelemetryRecorder *recorder, const MblinkTelemetrySessionMetadata *metadata, MblinkTelemetryTextSink sink, void *context);
bool mblink_telemetry_recorder_record_sample(MblinkTelemetryRecorder *recorder, const MblinkTelemetrySample *sample, bool favourite);
bool mblink_telemetry_recorder_record_response(MblinkTelemetryRecorder *recorder, uint64_t timestamp_ms, const char *command, const MblinkElm327Response *response);
bool mblink_telemetry_export_csv(const MblinkTelemetryStore *store, const MblinkTelemetrySessionMetadata *metadata, MblinkTelemetryTextSink sink, void *context);

#ifdef __cplusplus
}
#endif
#endif
