// SPDX-License-Identifier: GPL-3.0-or-later
/**
 * @file uds.h
 * @brief MBLINK compatibility aliases for LINK's shared ISO 14229 UDS engine.
 */
#ifndef MBLINK_UDS_H
#define MBLINK_UDS_H

#include "link/uds.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef LinkUdsResult MblinkUdsResult;
typedef LinkUdsResponseKind MblinkUdsResponseKind;
typedef LinkUdsResponse MblinkUdsResponse;
typedef LinkUdsSessionResponse MblinkUdsSessionResponse;
typedef LinkUdsDidRecord MblinkUdsDidRecord;
typedef LinkUdsDidDefinition MblinkUdsDidDefinition;
typedef LinkUdsDidValue MblinkUdsDidValue;
typedef LinkUdsClientConfig MblinkUdsClientConfig;
typedef LinkUdsClientState MblinkUdsClientState;
typedef LinkUdsClient MblinkUdsClient;

#define MBLINK_UDS_SERVICE_DIAGNOSTIC_SESSION_CONTROL LINK_UDS_SERVICE_DIAGNOSTIC_SESSION_CONTROL
#define MBLINK_UDS_SERVICE_READ_DATA_BY_IDENTIFIER LINK_UDS_SERVICE_READ_DATA_BY_IDENTIFIER
#define MBLINK_UDS_SERVICE_TESTER_PRESENT LINK_UDS_SERVICE_TESTER_PRESENT
#define MBLINK_UDS_SERVICE_NEGATIVE_RESPONSE LINK_UDS_SERVICE_NEGATIVE_RESPONSE
#define MBLINK_UDS_SESSION_DEFAULT LINK_UDS_SESSION_DEFAULT
#define MBLINK_UDS_SESSION_PROGRAMMING LINK_UDS_SESSION_PROGRAMMING
#define MBLINK_UDS_SESSION_EXTENDED LINK_UDS_SESSION_EXTENDED
#define MBLINK_UDS_SESSION_SAFETY_SYSTEM LINK_UDS_SESSION_SAFETY_SYSTEM
#define MBLINK_UDS_NRC_RESPONSE_PENDING LINK_UDS_NRC_RESPONSE_PENDING
#define MBLINK_UDS_RESULT_OK LINK_UDS_RESULT_OK
#define MBLINK_UDS_RESULT_COMPLETE LINK_UDS_RESULT_COMPLETE
#define MBLINK_UDS_RESULT_WAITING LINK_UDS_RESULT_WAITING
#define MBLINK_UDS_RESULT_RESPONSE_PENDING LINK_UDS_RESULT_RESPONSE_PENDING
#define MBLINK_UDS_RESULT_NEGATIVE_RESPONSE LINK_UDS_RESULT_NEGATIVE_RESPONSE
#define MBLINK_UDS_RESULT_INVALID_ARGUMENT LINK_UDS_RESULT_INVALID_ARGUMENT
#define MBLINK_UDS_RESULT_BUFFER_TOO_SMALL LINK_UDS_RESULT_BUFFER_TOO_SMALL
#define MBLINK_UDS_RESULT_MALFORMED_PDU LINK_UDS_RESULT_MALFORMED_PDU
#define MBLINK_UDS_RESULT_UNEXPECTED_RESPONSE LINK_UDS_RESULT_UNEXPECTED_RESPONSE
#define MBLINK_UDS_RESULT_BUSY LINK_UDS_RESULT_BUSY
#define MBLINK_UDS_RESULT_TIMEOUT LINK_UDS_RESULT_TIMEOUT
#define MBLINK_UDS_RESULT_FAILED_STATE LINK_UDS_RESULT_FAILED_STATE
#define MBLINK_UDS_RESULT_UNSUPPORTED LINK_UDS_RESULT_UNSUPPORTED
#define MBLINK_UDS_RESPONSE_POSITIVE LINK_UDS_RESPONSE_POSITIVE
#define MBLINK_UDS_RESPONSE_NEGATIVE LINK_UDS_RESPONSE_NEGATIVE
#define MBLINK_UDS_CLIENT_IDLE LINK_UDS_CLIENT_IDLE
#define MBLINK_UDS_CLIENT_WAITING_RESPONSE LINK_UDS_CLIENT_WAITING_RESPONSE
#define MBLINK_UDS_CLIENT_RESPONSE_PENDING LINK_UDS_CLIENT_RESPONSE_PENDING
#define MBLINK_UDS_CLIENT_COMPLETE LINK_UDS_CLIENT_COMPLETE
#define MBLINK_UDS_CLIENT_FAILED LINK_UDS_CLIENT_FAILED

#define mblink_uds_result_name link_uds_result_name
#define mblink_uds_client_state_name link_uds_client_state_name
#define mblink_uds_negative_response_code_name link_uds_negative_response_code_name
#define mblink_uds_decode_response link_uds_decode_response
#define mblink_uds_build_session_control_request link_uds_build_session_control_request
#define mblink_uds_decode_session_control_response link_uds_decode_session_control_response
#define mblink_uds_build_tester_present_request link_uds_build_tester_present_request
#define mblink_uds_decode_tester_present_response link_uds_decode_tester_present_response
#define mblink_uds_build_read_did_request link_uds_build_read_did_request
#define mblink_uds_decode_read_did_response link_uds_decode_read_did_response
#define mblink_uds_did_definition_is_valid link_uds_did_definition_is_valid
#define mblink_uds_build_defined_did_request link_uds_build_defined_did_request
#define mblink_uds_decode_defined_did_response link_uds_decode_defined_did_response
#define mblink_uds_client_init link_uds_client_init
#define mblink_uds_client_reset link_uds_client_reset
#define mblink_uds_client_begin link_uds_client_begin
#define mblink_uds_client_accept link_uds_client_accept
#define mblink_uds_client_tick link_uds_client_tick

#ifdef __cplusplus
}
#endif

#endif
