// SPDX-License-Identifier: GPL-3.0-or-later
/**
 * @file uds_services.h
 * @brief MBLINK compatibility facade for LINK's complete ISO 14229 service API.
 */
#ifndef MBLINK_UDS_SERVICES_H
#define MBLINK_UDS_SERVICES_H

#include "link/uds_services.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef LinkUdsServiceEffect MblinkUdsServiceEffect;
typedef LinkUdsServiceDefinition MblinkUdsServiceDefinition;
typedef LinkUdsRecordResponse MblinkUdsRecordResponse;

#define MBLINK_UDS_STANDARD_SERVICE_COUNT LINK_UDS_STANDARD_SERVICE_COUNT
#define MBLINK_UDS_SERVICE_DIAGNOSTIC_SESSION_CONTROL LINK_UDS_SERVICE_DIAGNOSTIC_SESSION_CONTROL
#define MBLINK_UDS_SERVICE_ECU_RESET LINK_UDS_SERVICE_ECU_RESET
#define MBLINK_UDS_SERVICE_CLEAR_DIAGNOSTIC_INFORMATION LINK_UDS_SERVICE_CLEAR_DIAGNOSTIC_INFORMATION
#define MBLINK_UDS_SERVICE_READ_DTC_INFORMATION LINK_UDS_SERVICE_READ_DTC_INFORMATION
#define MBLINK_UDS_SERVICE_READ_DATA_BY_IDENTIFIER LINK_UDS_SERVICE_READ_DATA_BY_IDENTIFIER
#define MBLINK_UDS_SERVICE_READ_MEMORY_BY_ADDRESS LINK_UDS_SERVICE_READ_MEMORY_BY_ADDRESS
#define MBLINK_UDS_SERVICE_READ_SCALING_DATA_BY_IDENTIFIER LINK_UDS_SERVICE_READ_SCALING_DATA_BY_IDENTIFIER
#define MBLINK_UDS_SERVICE_SECURITY_ACCESS LINK_UDS_SERVICE_SECURITY_ACCESS
#define MBLINK_UDS_SERVICE_COMMUNICATION_CONTROL LINK_UDS_SERVICE_COMMUNICATION_CONTROL
#define MBLINK_UDS_SERVICE_AUTHENTICATION LINK_UDS_SERVICE_AUTHENTICATION
#define MBLINK_UDS_SERVICE_READ_DATA_BY_PERIODIC_IDENTIFIER LINK_UDS_SERVICE_READ_DATA_BY_PERIODIC_IDENTIFIER
#define MBLINK_UDS_SERVICE_DYNAMICALLY_DEFINE_DATA_IDENTIFIER LINK_UDS_SERVICE_DYNAMICALLY_DEFINE_DATA_IDENTIFIER
#define MBLINK_UDS_SERVICE_WRITE_DATA_BY_IDENTIFIER LINK_UDS_SERVICE_WRITE_DATA_BY_IDENTIFIER
#define MBLINK_UDS_SERVICE_INPUT_OUTPUT_CONTROL_BY_IDENTIFIER LINK_UDS_SERVICE_INPUT_OUTPUT_CONTROL_BY_IDENTIFIER
#define MBLINK_UDS_SERVICE_ROUTINE_CONTROL LINK_UDS_SERVICE_ROUTINE_CONTROL
#define MBLINK_UDS_SERVICE_REQUEST_DOWNLOAD LINK_UDS_SERVICE_REQUEST_DOWNLOAD
#define MBLINK_UDS_SERVICE_REQUEST_UPLOAD LINK_UDS_SERVICE_REQUEST_UPLOAD
#define MBLINK_UDS_SERVICE_TRANSFER_DATA LINK_UDS_SERVICE_TRANSFER_DATA
#define MBLINK_UDS_SERVICE_REQUEST_TRANSFER_EXIT LINK_UDS_SERVICE_REQUEST_TRANSFER_EXIT
#define MBLINK_UDS_SERVICE_REQUEST_FILE_TRANSFER LINK_UDS_SERVICE_REQUEST_FILE_TRANSFER
#define MBLINK_UDS_SERVICE_WRITE_MEMORY_BY_ADDRESS LINK_UDS_SERVICE_WRITE_MEMORY_BY_ADDRESS
#define MBLINK_UDS_SERVICE_TESTER_PRESENT LINK_UDS_SERVICE_TESTER_PRESENT
#define MBLINK_UDS_SERVICE_ACCESS_TIMING_PARAMETER LINK_UDS_SERVICE_ACCESS_TIMING_PARAMETER
#define MBLINK_UDS_SERVICE_SECURED_DATA_TRANSMISSION LINK_UDS_SERVICE_SECURED_DATA_TRANSMISSION
#define MBLINK_UDS_SERVICE_CONTROL_DTC_SETTING LINK_UDS_SERVICE_CONTROL_DTC_SETTING
#define MBLINK_UDS_SERVICE_RESPONSE_ON_EVENT LINK_UDS_SERVICE_RESPONSE_ON_EVENT
#define MBLINK_UDS_SERVICE_LINK_CONTROL LINK_UDS_SERVICE_LINK_CONTROL

#define MBLINK_UDS_SERVICE_EFFECT_READ_ONLY LINK_UDS_SERVICE_EFFECT_READ_ONLY
#define MBLINK_UDS_SERVICE_EFFECT_SESSION_CONTROL LINK_UDS_SERVICE_EFFECT_SESSION_CONTROL
#define MBLINK_UDS_SERVICE_EFFECT_STATE_CHANGING LINK_UDS_SERVICE_EFFECT_STATE_CHANGING
#define MBLINK_UDS_SERVICE_EFFECT_SECURITY LINK_UDS_SERVICE_EFFECT_SECURITY
#define MBLINK_UDS_SERVICE_EFFECT_PROGRAMMING LINK_UDS_SERVICE_EFFECT_PROGRAMMING

#define MBLINK_UDS_ACCESS_TIMING_READ_EXTENDED_SET LINK_UDS_ACCESS_TIMING_READ_EXTENDED_SET
#define MBLINK_UDS_ACCESS_TIMING_SET_DEFAULT LINK_UDS_ACCESS_TIMING_SET_DEFAULT
#define MBLINK_UDS_ACCESS_TIMING_READ_ACTIVE LINK_UDS_ACCESS_TIMING_READ_ACTIVE
#define MBLINK_UDS_ACCESS_TIMING_SET_GIVEN LINK_UDS_ACCESS_TIMING_SET_GIVEN
#define MBLINK_UDS_DTC_SETTING_ON LINK_UDS_DTC_SETTING_ON
#define MBLINK_UDS_DTC_SETTING_OFF LINK_UDS_DTC_SETTING_OFF
#define MBLINK_UDS_ROUTINE_START LINK_UDS_ROUTINE_START
#define MBLINK_UDS_ROUTINE_STOP LINK_UDS_ROUTINE_STOP
#define MBLINK_UDS_ROUTINE_REQUEST_RESULTS LINK_UDS_ROUTINE_REQUEST_RESULTS
#define MBLINK_UDS_DYNAMIC_DID_DEFINE_BY_IDENTIFIER LINK_UDS_DYNAMIC_DID_DEFINE_BY_IDENTIFIER
#define MBLINK_UDS_DYNAMIC_DID_DEFINE_BY_MEMORY_ADDRESS LINK_UDS_DYNAMIC_DID_DEFINE_BY_MEMORY_ADDRESS
#define MBLINK_UDS_DYNAMIC_DID_CLEAR LINK_UDS_DYNAMIC_DID_CLEAR
#define MBLINK_UDS_LINK_VERIFY_FIXED_BAUDRATE LINK_UDS_LINK_VERIFY_FIXED_BAUDRATE
#define MBLINK_UDS_LINK_VERIFY_SPECIFIC_BAUDRATE LINK_UDS_LINK_VERIFY_SPECIFIC_BAUDRATE
#define MBLINK_UDS_LINK_TRANSITION_BAUDRATE LINK_UDS_LINK_TRANSITION_BAUDRATE
#define MBLINK_UDS_PERIODIC_SEND_SLOW LINK_UDS_PERIODIC_SEND_SLOW
#define MBLINK_UDS_PERIODIC_SEND_MEDIUM LINK_UDS_PERIODIC_SEND_MEDIUM
#define MBLINK_UDS_PERIODIC_SEND_FAST LINK_UDS_PERIODIC_SEND_FAST
#define MBLINK_UDS_PERIODIC_STOP LINK_UDS_PERIODIC_STOP

#define mblink_uds_standard_service_count link_uds_standard_service_count
#define mblink_uds_standard_service_at link_uds_standard_service_at
#define mblink_uds_standard_service_find link_uds_standard_service_find
#define mblink_uds_service_effect_name link_uds_service_effect_name
#define mblink_uds_build_registered_raw_request link_uds_build_registered_raw_request
#define mblink_uds_build_registered_subfunction_request link_uds_build_registered_subfunction_request
#define mblink_uds_decode_subfunction_response link_uds_decode_subfunction_response
#define mblink_uds_decode_did_response link_uds_decode_did_response
#define mblink_uds_decode_empty_service_response link_uds_decode_empty_service_response
#define mblink_uds_decode_transfer_data_response link_uds_decode_transfer_data_response
#define mblink_uds_decode_routine_control_response link_uds_decode_routine_control_response
#define mblink_uds_build_ecu_reset_request link_uds_build_ecu_reset_request
#define mblink_uds_build_clear_diagnostic_information_request link_uds_build_clear_diagnostic_information_request
#define mblink_uds_build_communication_control_request link_uds_build_communication_control_request
#define mblink_uds_build_read_memory_by_address_request link_uds_build_read_memory_by_address_request
#define mblink_uds_build_read_scaling_data_by_identifier_request link_uds_build_read_scaling_data_by_identifier_request
#define mblink_uds_build_security_access_request link_uds_build_security_access_request
#define mblink_uds_build_authentication_request link_uds_build_authentication_request
#define mblink_uds_build_read_data_by_periodic_identifier_request link_uds_build_read_data_by_periodic_identifier_request
#define mblink_uds_build_dynamically_define_data_identifier_request link_uds_build_dynamically_define_data_identifier_request
#define mblink_uds_build_write_data_by_identifier_request link_uds_build_write_data_by_identifier_request
#define mblink_uds_build_input_output_control_by_identifier_request link_uds_build_input_output_control_by_identifier_request
#define mblink_uds_build_routine_control_request link_uds_build_routine_control_request
#define mblink_uds_build_request_download_request link_uds_build_request_download_request
#define mblink_uds_build_request_upload_request link_uds_build_request_upload_request
#define mblink_uds_build_transfer_data_request link_uds_build_transfer_data_request
#define mblink_uds_build_request_transfer_exit_request link_uds_build_request_transfer_exit_request
#define mblink_uds_build_request_file_transfer_request link_uds_build_request_file_transfer_request
#define mblink_uds_build_write_memory_by_address_request link_uds_build_write_memory_by_address_request
#define mblink_uds_build_access_timing_parameter_request link_uds_build_access_timing_parameter_request
#define mblink_uds_build_secured_data_transmission_request link_uds_build_secured_data_transmission_request
#define mblink_uds_build_control_dtc_setting_request link_uds_build_control_dtc_setting_request
#define mblink_uds_build_response_on_event_request link_uds_build_response_on_event_request
#define mblink_uds_build_link_control_request link_uds_build_link_control_request

#ifdef __cplusplus
}
#endif

#endif
