// SPDX-License-Identifier: GPL-3.0-or-later
/**
 * @file uds_authentication.h
 * @brief MBLINK facade for LINK's ISO 14229-1:2020 Authentication codec.
 *
 * LINK owns framing and strict structural validation. Certificate parsing,
 * trust anchors, private keys, cryptographic verification and Mercedes/OEM
 * policy remain product-owned and are not invented here.
 */
#ifndef MBLINK_UDS_AUTHENTICATION_H
#define MBLINK_UDS_AUTHENTICATION_H

#include "mblink/uds.h"
#include "link/uds_authentication.h"

#ifdef __cplusplus
extern "C" {
#endif

#define MBLINK_UDS_AUTH_DEAUTHENTICATE LINK_UDS_AUTH_DEAUTHENTICATE
#define MBLINK_UDS_AUTH_VERIFY_CERTIFICATE_UNIDIRECTIONAL LINK_UDS_AUTH_VERIFY_CERTIFICATE_UNIDIRECTIONAL
#define MBLINK_UDS_AUTH_VERIFY_CERTIFICATE_BIDIRECTIONAL LINK_UDS_AUTH_VERIFY_CERTIFICATE_BIDIRECTIONAL
#define MBLINK_UDS_AUTH_PROOF_OF_OWNERSHIP LINK_UDS_AUTH_PROOF_OF_OWNERSHIP
#define MBLINK_UDS_AUTH_TRANSMIT_CERTIFICATE LINK_UDS_AUTH_TRANSMIT_CERTIFICATE
#define MBLINK_UDS_AUTH_REQUEST_CHALLENGE LINK_UDS_AUTH_REQUEST_CHALLENGE
#define MBLINK_UDS_AUTH_VERIFY_PROOF_UNIDIRECTIONAL LINK_UDS_AUTH_VERIFY_PROOF_UNIDIRECTIONAL
#define MBLINK_UDS_AUTH_VERIFY_PROOF_BIDIRECTIONAL LINK_UDS_AUTH_VERIFY_PROOF_BIDIRECTIONAL
#define MBLINK_UDS_AUTH_CONFIGURATION LINK_UDS_AUTH_CONFIGURATION
#define MBLINK_UDS_AUTH_ALGORITHM_INDICATOR_BYTES LINK_UDS_AUTH_ALGORITHM_INDICATOR_BYTES

#define MBLINK_UDS_AUTH_RETURN_REQUEST_ACCEPTED LINK_UDS_AUTH_RETURN_REQUEST_ACCEPTED
#define MBLINK_UDS_AUTH_RETURN_GENERAL_REJECT LINK_UDS_AUTH_RETURN_GENERAL_REJECT
#define MBLINK_UDS_AUTH_RETURN_CONFIGURATION LINK_UDS_AUTH_RETURN_CONFIGURATION
#define MBLINK_UDS_AUTH_RETURN_CONFIGURATION_ACR_ASYMMETRIC LINK_UDS_AUTH_RETURN_CONFIGURATION_ACR_ASYMMETRIC
#define MBLINK_UDS_AUTH_RETURN_CONFIGURATION_ACR_SYMMETRIC LINK_UDS_AUTH_RETURN_CONFIGURATION_ACR_SYMMETRIC
#define MBLINK_UDS_AUTH_RETURN_DEAUTHENTICATED LINK_UDS_AUTH_RETURN_DEAUTHENTICATED
#define MBLINK_UDS_AUTH_RETURN_CERTIFICATE_VERIFIED_OWNERSHIP_REQUIRED LINK_UDS_AUTH_RETURN_CERTIFICATE_VERIFIED_OWNERSHIP_REQUIRED
#define MBLINK_UDS_AUTH_RETURN_OWNERSHIP_VERIFIED_COMPLETE LINK_UDS_AUTH_RETURN_OWNERSHIP_VERIFIED_COMPLETE
#define MBLINK_UDS_AUTH_RETURN_CERTIFICATE_VERIFIED LINK_UDS_AUTH_RETURN_CERTIFICATE_VERIFIED

typedef LinkUdsAuthenticationSpan MblinkUdsAuthenticationSpan;
typedef LinkUdsAuthenticationResponse MblinkUdsAuthenticationResponse;

#define mblink_uds_build_authentication_deauthenticate_request link_uds_build_authentication_deauthenticate_request
#define mblink_uds_build_authentication_verify_certificate_request link_uds_build_authentication_verify_certificate_request
#define mblink_uds_build_authentication_proof_of_ownership_request link_uds_build_authentication_proof_of_ownership_request
#define mblink_uds_build_authentication_transmit_certificate_request link_uds_build_authentication_transmit_certificate_request
#define mblink_uds_build_authentication_request_challenge_request link_uds_build_authentication_request_challenge_request
#define mblink_uds_build_authentication_verify_proof_request link_uds_build_authentication_verify_proof_request
#define mblink_uds_build_authentication_configuration_request link_uds_build_authentication_configuration_request
#define mblink_uds_decode_authentication_response link_uds_decode_authentication_response

#ifdef __cplusplus
}
#endif

#endif
