// SPDX-License-Identifier: GPL-3.0-or-later
/**
 * @file uds_dtc.h
 * @brief MBLINK compatibility aliases for LINK's shared ReadDTCInformation codec.
 */
#ifndef MBLINK_UDS_DTC_H
#define MBLINK_UDS_DTC_H

#include "mblink/uds.h"
#include "link/uds_dtc.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef LinkUdsDtcRecord MblinkUdsDtcRecord;
typedef LinkUdsDtcList MblinkUdsDtcList;

#define MBLINK_UDS_SERVICE_READ_DTC_INFORMATION LINK_UDS_SERVICE_READ_DTC_INFORMATION
#define MBLINK_UDS_DTC_REPORT_BY_STATUS_MASK LINK_UDS_DTC_REPORT_BY_STATUS_MASK
#define MBLINK_UDS_DTC_STATUS_MASK_ALL LINK_UDS_DTC_STATUS_MASK_ALL
#define MBLINK_UDS_DTC_MAX_RECORDS LINK_UDS_DTC_MAX_RECORDS
#define MBLINK_UDS_DTC_STATUS_TEST_FAILED LINK_UDS_DTC_STATUS_TEST_FAILED
#define MBLINK_UDS_DTC_STATUS_TEST_FAILED_THIS_OPERATION_CYCLE LINK_UDS_DTC_STATUS_TEST_FAILED_THIS_OPERATION_CYCLE
#define MBLINK_UDS_DTC_STATUS_PENDING_DTC LINK_UDS_DTC_STATUS_PENDING_DTC
#define MBLINK_UDS_DTC_STATUS_CONFIRMED_DTC LINK_UDS_DTC_STATUS_CONFIRMED_DTC
#define MBLINK_UDS_DTC_STATUS_TEST_NOT_COMPLETED_SINCE_LAST_CLEAR LINK_UDS_DTC_STATUS_TEST_NOT_COMPLETED_SINCE_LAST_CLEAR
#define MBLINK_UDS_DTC_STATUS_TEST_FAILED_SINCE_LAST_CLEAR LINK_UDS_DTC_STATUS_TEST_FAILED_SINCE_LAST_CLEAR
#define MBLINK_UDS_DTC_STATUS_TEST_NOT_COMPLETED_THIS_OPERATION_CYCLE LINK_UDS_DTC_STATUS_TEST_NOT_COMPLETED_THIS_OPERATION_CYCLE
#define MBLINK_UDS_DTC_STATUS_WARNING_INDICATOR_REQUESTED LINK_UDS_DTC_STATUS_WARNING_INDICATOR_REQUESTED

#define mblink_uds_build_report_dtcs_by_status_mask_request link_uds_build_report_dtcs_by_status_mask_request
#define mblink_uds_decode_report_dtcs_by_status_mask_response link_uds_decode_report_dtcs_by_status_mask_response
#define mblink_uds_dtc_status_matches link_uds_dtc_status_matches
#define mblink_uds_dtc_format_hex link_uds_dtc_format_hex

#ifdef __cplusplus
}
#endif

#endif
