// SPDX-License-Identifier: GPL-3.0-or-later
/**
 * @file uds_bootloader.h
 * @brief MBLINK facade for LINK's fail-closed UDS OTA/bootloader core.
 *
 * The shared core enforces programming sequence, A/B staging, anti-rollback,
 * transfer ordering and verification gates. Hardware flash/HSM operations stay
 * target-owned and programming remains disabled by default.
 */
#ifndef MBLINK_UDS_BOOTLOADER_H
#define MBLINK_UDS_BOOTLOADER_H

#include "link/uds_bootloader.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef LinkUdsBootloaderResult MblinkUdsBootloaderResult;
typedef LinkUdsBootloaderState MblinkUdsBootloaderState;
typedef LinkUdsBootloaderBackend MblinkUdsBootloaderBackend;
typedef LinkUdsBootloaderConfig MblinkUdsBootloaderConfig;
typedef LinkUdsBootloader MblinkUdsBootloader;

#define MBLINK_UDS_BOOTLOADER_SLOT_NONE LINK_UDS_BOOTLOADER_SLOT_NONE

#define MBLINK_UDS_BOOTLOADER_RESULT_OK LINK_UDS_BOOTLOADER_RESULT_OK
#define MBLINK_UDS_BOOTLOADER_RESULT_INVALID_ARGUMENT LINK_UDS_BOOTLOADER_RESULT_INVALID_ARGUMENT
#define MBLINK_UDS_BOOTLOADER_RESULT_LOCKED LINK_UDS_BOOTLOADER_RESULT_LOCKED
#define MBLINK_UDS_BOOTLOADER_RESULT_BAD_STATE LINK_UDS_BOOTLOADER_RESULT_BAD_STATE
#define MBLINK_UDS_BOOTLOADER_RESULT_SEQUENCE_ERROR LINK_UDS_BOOTLOADER_RESULT_SEQUENCE_ERROR
#define MBLINK_UDS_BOOTLOADER_RESULT_SIZE_MISMATCH LINK_UDS_BOOTLOADER_RESULT_SIZE_MISMATCH
#define MBLINK_UDS_BOOTLOADER_RESULT_ROLLBACK_REJECTED LINK_UDS_BOOTLOADER_RESULT_ROLLBACK_REJECTED
#define MBLINK_UDS_BOOTLOADER_RESULT_BACKEND_FAILURE LINK_UDS_BOOTLOADER_RESULT_BACKEND_FAILURE
#define MBLINK_UDS_BOOTLOADER_RESULT_INTEGRITY_FAILED LINK_UDS_BOOTLOADER_RESULT_INTEGRITY_FAILED
#define MBLINK_UDS_BOOTLOADER_RESULT_AUTHENTICITY_FAILED LINK_UDS_BOOTLOADER_RESULT_AUTHENTICITY_FAILED
#define MBLINK_UDS_BOOTLOADER_RESULT_SECURE_BOOT_FAILED LINK_UDS_BOOTLOADER_RESULT_SECURE_BOOT_FAILED

#define MBLINK_UDS_BOOTLOADER_STATE_DISARMED LINK_UDS_BOOTLOADER_STATE_DISARMED
#define MBLINK_UDS_BOOTLOADER_STATE_ARMED LINK_UDS_BOOTLOADER_STATE_ARMED
#define MBLINK_UDS_BOOTLOADER_STATE_PROGRAMMING_SESSION LINK_UDS_BOOTLOADER_STATE_PROGRAMMING_SESSION
#define MBLINK_UDS_BOOTLOADER_STATE_SECURITY_GRANTED LINK_UDS_BOOTLOADER_STATE_SECURITY_GRANTED
#define MBLINK_UDS_BOOTLOADER_STATE_QUIESCED LINK_UDS_BOOTLOADER_STATE_QUIESCED
#define MBLINK_UDS_BOOTLOADER_STATE_DOWNLOADING LINK_UDS_BOOTLOADER_STATE_DOWNLOADING
#define MBLINK_UDS_BOOTLOADER_STATE_TRANSFER_COMPLETE LINK_UDS_BOOTLOADER_STATE_TRANSFER_COMPLETE
#define MBLINK_UDS_BOOTLOADER_STATE_VERIFIED LINK_UDS_BOOTLOADER_STATE_VERIFIED
#define MBLINK_UDS_BOOTLOADER_STATE_STAGED LINK_UDS_BOOTLOADER_STATE_STAGED
#define MBLINK_UDS_BOOTLOADER_STATE_COMPLETE LINK_UDS_BOOTLOADER_STATE_COMPLETE
#define MBLINK_UDS_BOOTLOADER_STATE_FAILED LINK_UDS_BOOTLOADER_STATE_FAILED

#define MBLINK_UDS_BOOTLOADER_CONFIG_INIT LINK_UDS_BOOTLOADER_CONFIG_INIT

#define mblink_uds_bootloader_init link_uds_bootloader_init
#define mblink_uds_bootloader_arm link_uds_bootloader_arm
#define mblink_uds_bootloader_enter_programming_session link_uds_bootloader_enter_programming_session
#define mblink_uds_bootloader_grant_security link_uds_bootloader_grant_security
#define mblink_uds_bootloader_set_dtc_recording_disabled link_uds_bootloader_set_dtc_recording_disabled
#define mblink_uds_bootloader_set_communication_disabled link_uds_bootloader_set_communication_disabled
#define mblink_uds_bootloader_request_download link_uds_bootloader_request_download
#define mblink_uds_bootloader_transfer_data link_uds_bootloader_transfer_data
#define mblink_uds_bootloader_request_transfer_exit link_uds_bootloader_request_transfer_exit
#define mblink_uds_bootloader_check_memory link_uds_bootloader_check_memory
#define mblink_uds_bootloader_stage_for_reset link_uds_bootloader_stage_for_reset
#define mblink_uds_bootloader_confirm_boot link_uds_bootloader_confirm_boot
#define mblink_uds_bootloader_abort link_uds_bootloader_abort

#ifdef __cplusplus
}
#endif

#endif
